apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    virtual-server.f5.com/multiClusterServices: '[
    {"clusterName": "openshift-4-15", "service": "coffee-svc", "namespace": "default", "servicePort": "8080", "weight": 100}, 
    {"clusterName": "openshift-4-15-cm", "service": "coffee-svc", "namespace": "default", "servicePort": "8080", "weight": 0}
    ]'
  labels:
    f5type: systest
  name: coffee
spec:
  host: cafe.example.com
  path: /coffee
  port:
    targetPort: 8080
  to:
    kind: Service
    name: coffee-svc
    weight: 0