apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-app
  name: hello-world-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world-app
    spec:
      containers:
      - env:
        - name: service_name
          value: hello-world-app
        image: f5devcentral/f5-hello-world:latest
        imagePullPolicy: Always
        name: hello-world-app
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: hello-world-app
  name: hello-world-app
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 31139
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-app
  type: NodePort