apiVersion: v1
items:
  - apiVersion: cis.f5.com/v1
    kind: TransportServer
    metadata:
      labels:
        f5cr: "true"
      name: coffee
      namespace: default
    spec:
      mode: standard
      pool:
        service: coffee-svc
        servicePort: 8080
      snat: auto
      type: tcp
      virtualServerAddress: 10.192.125.65
      virtualServerPort: 80
kind: List
metadata:
  resourceVersion: ""
