apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: global-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    mode: ratio
    externalClustersConfig:
    - clusterName: openshift-4-15
      secret: default/openshift-4-15
    - clusterName: openshift-4-15-cm
      secret: default/openshift-4-15-cm
    extendedRouteSpec:
    - namespace: default
      vserverAddr: 10.192.125.65
      vserverName: cafe
      allowOverride: false