apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-app-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-app-nginx
            port:
              number: 80