apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    f5nr: "true"
  name: global-spec-config
  namespace: kube-system
data:
  extendedSpec: |
    highAvailabilityCIS:
      primaryCluster:
        clusterName: local-cluster
        secret: default/openshift-4-14
    externalClustersConfig:
    - clusterName: ocp-pm
      secret: default/openshift-4-11
    extendedRouteSpec:
    - namespace: default
      vserverAddr: 10.192.125.65
      vserverName: cafe
      allowOverride: false